### ISSUE TITLE
Docker demo doesn't work

### ISSUE THREAD

**Issue by sinacek** [helix-iot/helix-sandbox#1]
Hi,
I tried https://github.com/helix-iot/helix-sandbox/blob/master/docs/accessing.md but i don't expected result. 

I see in my browser on http://localhost:5000/:
![mozilla firefox](https://user-images.githubusercontent.com/1140123/48711893-ac57d480-ec0c-11e8-9dbb-6c0c591dfa27.jpg)

Do you have any idea?

**Comment by m4n3dw0lf** [comment]
Hi, how did you perfomed the deployment?

**Comment by sinacek** [comment]
`docker-compose up -d`

**Comment by m4n3dw0lf** [comment]
the pre-reqs have been set? https://github.com/helix-iot/helix-sandbox/blob/master/docs/requirements.md

**Comment by m4n3dw0lf** [comment]
@sinacek , i believe that it's a port conflict, can you add a port parameter on the helix container docker-compose.yml to use the port <another_port>:5000 instead of 5000:5000, and access through http://localhost:<another_port> ?

**Comment by sinacek** [comment]
Thanks, It helps
